export const actionTypes = {
  ACCEPT: 'WALL/PROFILES/ACCEPT',
  DISMISS: 'WALL/PROFILES/DISMISS',
  DELETE_CURRENT: 'WALL/PROFILES/DELETE_CURRENT',
  SET_CURRENT: 'WALL/PROFILES/SET_CURRENT',
};

export const KEY = 'wallProfiles';
