export const actionTypes = {
  FETCH: 'WALL/QUERY/FETCH',
  FETCH_SUCCESS: 'WALL/QUERY/FETCH_SUCCESS',
  FETCH_ERROR: 'WALL/QUERY/FETCH_ERROR',
  CANCEL: 'WALL/QUERY/CANCEL',
};

export const KEY = 'wallQuery';
